name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        apt-get update 
        apt-get upgrade -yq 
        apt-get install --yes --no-install-recommends \
          ca-certificates \
          wget \
          git \
          gcc-12 \
          g++-12 \
          clang-15 \
          libc++-15-dev \
          libc++abi-15-dev \
          clang-format-15 \
          clang-tidy-15 \
          cmake \
          cppcheck \
          ninja-build \
          xorg-dev \
          pocl-opencl-icd \
          ocl-icd-opencl-dev \
        apt-get clean 
        rm -rf 
        /var/lib/apt/lists/* 
        /var/cache/debconf 
        /tmp/* 
        cd ~ 
        git clone https://github.com/google/googletest.git 
        cd googletest
        mkdir build
        cd build
        CC=clang-15 CXX=clang++-15 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target install 
        cd ..
        cd .. 
        rm -rf googletest
    - name: Run tests
      run: |
        cd docker
        python3 run_tests.py
