name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd docker
        docker build -t nsttf/nsttf:1.0 -f Dockerfile .
    - name: run_tests.py
      run: |
        docker run --rm --name=nsttf --mount type=bind,source="${PWD}/..",target=/src nsttf/nsttf:1.0 \
          python3 src/NSTTF/docker/run_tests.py
    
